import os


PATTERN_ID = "diamond"
LABEL = "Diamond Pattern"
ICON = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "resources", "icons", "diamond.svg")
DEFAULT_DIAMOND_HEIGHT = 12.0
MIN_DIAMOND_HEIGHT = 0.01
MAX_DIAMOND_HEIGHT = 1000.0
DEFAULT_PYRAMID_HEIGHT = 1.5
MIN_PYRAMID_HEIGHT = 0.01
MAX_PYRAMID_HEIGHT = 1000.0
DEFAULT_CLOSURE_FIT_TOLERANCE = 0.20
MIN_CLOSURE_FIT_TOLERANCE = 0.0
MAX_CLOSURE_FIT_TOLERANCE = 1000.0
DEFAULT_CURVED_RELIEF_FACTOR = 0.50
MIN_CURVED_RELIEF_FACTOR = 0.05
MAX_CURVED_RELIEF_FACTOR = 1.0
DEFAULT_CELL_GAP = 0.40
DEFAULT_CELL_GAP_X = DEFAULT_CELL_GAP
DEFAULT_CELL_GAP_Y = DEFAULT_CELL_GAP
MIN_CELL_GAP = 0.0
MAX_CELL_GAP = 5.0

# Compatibility aliases for callers written before the two dimensions were
# exposed separately.
DEFAULT_HEIGHT = DEFAULT_PYRAMID_HEIGHT
MIN_HEIGHT = MIN_PYRAMID_HEIGHT
MAX_HEIGHT = MAX_PYRAMID_HEIGHT
